<?php include('header.phtml'); ?>
    <style type="text/css">
        .starter-template {
            padding: 3rem 1.5rem;
            text-align: center;
        }
        .yolk {
            margin: 0 auto;
            width: 240px;
            height: 240px;
            border-radius: 50%;
            background: #FFDF50;
            border-radius: 100%;
            box-shadow: inset -12px -12px #F1AD41;
        }
    </style>
    <div class="starter-template">
        <h1>MortAl mage aGEnts</h1>
        <p class="lead">
            MortAl mage aGEnts is a wallet service that can trade "magecoin"<br>
            We give 100000000MGC to the initial registrant now.
        </p>
        <div class="yolk"></div>
    </div>
<?php include('footer.phtml'); ?>
